# GitHub Actions workflow for govulncheck.
# This file is licensed under MIT License.
# https://github.com/fxamacker/cbor

name: govulncheck

# Revoke default permissions and grant what's needed in each job.
permissions: {}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**'
      - '!**.md'
  push:
    paths:
      - '**'
      - '!**.md'
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      # Grant permission to read content.
      contents: read
    steps:
    - name: Checkout source
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  #v4.1.6
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7  #v5.0.1
      with:
        go-version: 1.22.x
        check-latest: true
    - name: Install latest from golang.org
      run: go install golang.org/x/vuln/cmd/govulncheck@latest # latest
    - name: Run govulncheck      
      run: govulncheck -show=traces ./...
